---
title: "Homework10"
author: "Akash Setti, Anuraag Pujari, Gauthaman Sethupathy, Siddarthan Prakash"
date: "4/20/2022"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
```


```{r}
df <- read.csv("accident.csv")
head(df)
df %>% ggplot(aes(x = LONGITUD, y = LATITUDE)) + geom_point()
```


```{r, echo=TRUE}
df %>% ggplot(aes(x = DAY_WEEK)) + geom_bar()
table(df$DAY_WEEK)

df %>% ggplot(aes(x = HOUR)) + geom_bar()
table(df$HOUR)

df %>% ggplot(aes(x = DRUNK_DR)) + geom_bar()
table(df$DRUNK_DR)
```


There are more accidents on the 7th day on the week than any other day.
The most accidents also happen during night time, between 17-20 hr with them all being above 1900.
There are 12,453 number of accidents with at least 1 one drunk driver.

```{r, echo=TRUE}
df2 <- read.csv("person.csv")
head(df2)
new_df2 <- df2 %>% filter(PER_TYP %in% c(1))
head(new_df2)
```
```{r}
df3 <- merge(df,new_df2, by =c("ST_CASE"))
head(df3)
```




```{r, echo=TRUE}
df3 %>% ggplot(aes(x = DAY_WEEK)) + geom_bar()
table(df3$DAY_WEEK)

df3 %>% ggplot(aes(x = HOUR.x)) + geom_bar()

df3 %>% ggplot(aes(x = SEX)) + geom_bar()
table(df3$SEX)
```


github link: https://github.com/asetti2002/DS202Homework10

